stages:
  data_ingestion:
    cmd: python src/DataIngestion.py
    deps:
      - src/DataIngestion.py
    outs:
      - data/raw_data.csv

  data_splitting:
    cmd: python src/DataSplit.py
    deps:
      - src/DataSplit.py
      - data/raw_data.csv
    outs:
      - data/train_data.csv
      - data/test_data.csv
      
  data_preprocessing:
    cmd: python src/DataFeatureEngineering.py
    deps:
      - src/DataFeatureEngineering.py
      - data/train_data.csv
      - data/test_data.csv
    outs:
      - data/train_data_scaled.csv
      - data/test_data_scaled.csv

  model_training:
    cmd: python src/Model.py
    deps:
      - src/Model.py
      - data/train_data_scaled.csv
    params:
      - experiment_name
      - ${experiment_name}  # <-- DVC dynamically tracks only the active model's params!
    outs:
      - models/${experiment_name}.h5  # <-- DVC dynamically expects only the active model's file!