stages:
  data_ingestion:
    cmd: python src/DataIngetion.py
    deps:
      - src/DataIngetion.py
    outs:
      - data/raw_data.csv

  data_splitting:
    cmd: python src/DataSplit.py
    deps:
      - src/DataSplit.py
      - data/raw_data.csv
    outs:
      - data/train_data.csv
      - data/test_data.csv
      
  data_preprocessing:
    cmd: python src/DataFeatureEngineering.py
    deps:
      - src/DataFeatureEngineering.py
      - data/train_data.csv
      - data/test_data.csv
    outs:
      - data/train_data_scaled.csv
      - data/test_data_scaled.csv

  model_training:
    cmd: python src/Model.py
    deps:
      - src/Model.py
      - data/train_data_scaled.csv
    params:
      - experiment_name
      - baseline_model
    outs:
      - models/baseline_model.h5