name: Continuous Deployment to AWS

on:
  push:
    branches:
      - main  # (If your default branch is 'master', change this to master)

jobs:
  deploy:
    name: Deploy API to EC2
    runs-on: ubuntu-latest

    steps:
      - name: SSH into AWS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Download the code if it doesn't exist, otherwise just open the folder
            if [ ! -d "End_To_End_Credit_Card_Fraud_Detection_System" ]; then
              git clone https://github.com/${{ github.repository }}.git End_To_End_Credit_Card_Fraud_Detection_System
            fi
            
            # 2. Go into the project folder and pull your newest updates
            cd End_To_End_Credit_Card_Fraud_Detection_System
            git pull origin main
            
            # 3. Gracefully stop and delete the old API (|| true prevents crashing on the first run)
            sudo docker stop live-api || true
            sudo docker rm live-api || true
            
            # 4. Forging the new container with your updated code
            sudo docker build -t my-fraud-api:v1 .
            
            # 5. The Immortal Launch
            sudo docker run -d -p 8000:8000 --name live-api my-fraud-api:v1